# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dialog.ui'
#
# Created by: PyQt4 UI code generator 4.12.dev1606101416
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(362, 276)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.ttime = QtGui.QLabel(Dialog)
        self.ttime.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.ttime.setObjectName(_fromUtf8("ttime"))
        self.lptime = QtGui.QLabel(Dialog)
        self.lptime.setGeometry(QtCore.QRect(12, 70, 101, 16))
        self.lptime.setObjectName(_fromUtf8("lptime"))
        self.sptime = QtGui.QLabel(Dialog)
        self.sptime.setGeometry(QtCore.QRect(12, 110, 101, 16))
        self.sptime.setObjectName(_fromUtf8("sptime"))
        self.spinTomat = QtGui.QSpinBox(Dialog)
        self.spinTomat.setGeometry(QtCore.QRect(118, 30, 41, 22))
        self.spinTomat.setMinimum(1)
        self.spinTomat.setObjectName(_fromUtf8("spinTomat"))
        self.spinShort = QtGui.QSpinBox(Dialog)
        self.spinShort.setGeometry(QtCore.QRect(120, 110, 41, 22))
        self.spinShort.setMinimum(1)
        self.spinShort.setObjectName(_fromUtf8("spinShort"))
        self.spinLong = QtGui.QSpinBox(Dialog)
        self.spinLong.setGeometry(QtCore.QRect(120, 70, 41, 22))
        self.spinLong.setMinimum(1)
        self.spinLong.setObjectName(_fromUtf8("spinLong"))
        self.btnCnl = QtGui.QPushButton(Dialog)
        self.btnCnl.setGeometry(QtCore.QRect(190, 240, 75, 26))
        self.btnCnl.setObjectName(_fromUtf8("btnCnl"))
        self.btnOk = QtGui.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(270, 240, 75, 26))
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.run_label = QtGui.QLabel(Dialog)
        self.run_label.setGeometry(QtCore.QRect(190, 10, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.run_label.setFont(font)
        self.run_label.setObjectName(_fromUtf8("run_label"))
        self.start_run = QtGui.QCheckBox(Dialog)
        self.start_run.setGeometry(QtCore.QRect(190, 30, 121, 20))
        self.start_run.setObjectName(_fromUtf8("start_run"))
        self.finish_run = QtGui.QCheckBox(Dialog)
        self.finish_run.setGeometry(QtCore.QRect(190, 80, 131, 20))
        self.finish_run.setObjectName(_fromUtf8("finish_run"))
        self.start_edit = QtGui.QLineEdit(Dialog)
        self.start_edit.setEnabled(False)
        self.start_edit.setGeometry(QtCore.QRect(210, 50, 141, 22))
        self.start_edit.setObjectName(_fromUtf8("start_edit"))
        self.finish_edit = QtGui.QLineEdit(Dialog)
        self.finish_edit.setEnabled(False)
        self.finish_edit.setGeometry(QtCore.QRect(210, 110, 141, 22))
        self.finish_edit.setObjectName(_fromUtf8("finish_edit"))
        self.scut_label = QtGui.QLabel(Dialog)
        self.scut_label.setGeometry(QtCore.QRect(10, 150, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scut_label.setFont(font)
        self.scut_label.setObjectName(_fromUtf8("scut_label"))
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(150, 170, 21, 16))
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setMaxLength(32767)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.time_label = QtGui.QLabel(Dialog)
        self.time_label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setObjectName(_fromUtf8("time_label"))
        self.sc_st_lb = QtGui.QLabel(Dialog)
        self.sc_st_lb.setGeometry(QtCore.QRect(10, 170, 81, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.sc_st_lb.setFont(font)
        self.sc_st_lb.setObjectName(_fromUtf8("sc_st_lb"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 130, 341, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(100, 170, 52, 14))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sc_sp_lb = QtGui.QLabel(Dialog)
        self.sc_sp_lb.setGeometry(QtCore.QRect(10, 200, 81, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.sc_sp_lb.setFont(font)
        self.sc_sp_lb.setObjectName(_fromUtf8("sc_sp_lb"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(100, 200, 51, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_5 = QtGui.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 200, 21, 16))
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_5.setText(_fromUtf8(""))
        self.lineEdit_5.setMaxLength(32767)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.sc_spau_lb = QtGui.QLabel(Dialog)
        self.sc_spau_lb.setGeometry(QtCore.QRect(200, 170, 71, 16))
        self.sc_spau_lb.setObjectName(_fromUtf8("sc_spau_lb"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(280, 170, 52, 14))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(280, 200, 52, 14))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 170, 21, 16))
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_2.setText(_fromUtf8(""))
        self.lineEdit_2.setMaxLength(32767)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_6 = QtGui.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(330, 200, 21, 16))
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setMaxLength(32767)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.sc_lpau_lb = QtGui.QLabel(Dialog)
        self.sc_lpau_lb.setGeometry(QtCore.QRect(200, 200, 71, 16))
        self.sc_lpau_lb.setObjectName(_fromUtf8("sc_lpau_lb"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.start_run, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.start_edit.setEnabled)
        QtCore.QObject.connect(self.finish_run, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.finish_edit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.spinTomat, self.spinLong)
        Dialog.setTabOrder(self.spinLong, self.spinShort)
        Dialog.setTabOrder(self.spinShort, self.btnOk)
        Dialog.setTabOrder(self.btnOk, self.btnCnl)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.ttime.setText(_translate("Dialog", "Tomato Time", None))
        self.lptime.setText(_translate("Dialog", "Long Pause Time", None))
        self.sptime.setText(_translate("Dialog", "Short Pause Time", None))
        self.btnCnl.setText(_translate("Dialog", "Cancel", None))
        self.btnOk.setText(_translate("Dialog", "Ok", None))
        self.run_label.setText(_translate("Dialog", "Run commands:", None))
        self.start_run.setText(_translate("Dialog", "with start pomidor", None))
        self.finish_run.setText(_translate("Dialog", "when finish pomidor", None))
        self.scut_label.setText(_translate("Dialog", "Shortcuts:", None))
        self.time_label.setText(_translate("Dialog", "Time settings:", None))
        self.sc_st_lb.setText(_translate("Dialog", "Start Tomacco ", None))
        self.label_7.setText(_translate("Dialog", " Ctrl+Alt+", None))
        self.sc_sp_lb.setText(_translate("Dialog", "Stop Tomacco ", None))
        self.label_9.setText(_translate("Dialog", " Ctrl+Alt+", None))
        self.sc_spau_lb.setText(_translate("Dialog", "Short Pause", None))
        self.label_10.setText(_translate("Dialog", " Ctrl+Alt+", None))
        self.label_11.setText(_translate("Dialog", " Ctrl+Alt+", None))
        self.sc_lpau_lb.setText(_translate("Dialog", "Long Pause", None))

